### ISSUE TITLE
Høsting av modeller feiler med "java.io.FileNotFoundException: https://fdk-dev-altinn.appspot.com/api/v1/schemas"

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-informationmodel-harvester#8]
```
2020-01-21 06:10:00.197 DEBUG 6 --- [pool-1-thread-1] no.fdk.imcat.service.AltinnHarvest       : Getting harvest sources from AltInn
2020-01-21 06:10:00.197 DEBUG 6 --- [pool-1-thread-1] no.fdk.imcat.service.AltinnHarvest       : Retrieving all schemas from altinn.  url: https://fdk-dev-altinn.appspot.com/api/v1/schemas Expected load time approx 5 minutes
2020-01-21 06:10:05.964 DEBUG 6 --- [pool-1-thread-1] no.fdk.imcat.service.AltinnHarvest       : Failed while reading information models from  

java.io.FileNotFoundException: https://fdk-dev-altinn.appspot.com/api/v1/schemas
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896) ~[na:1.8.0_232]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_232]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[na:1.8.0_232]
	at java.net.URL.openStream(URL.java:1067) ~[na:1.8.0_232]
	at no.fdk.imcat.service.AltinnHarvest.loadAllInformationModelsFromOurAltInnAdapter(AltinnHarvest.java:139) [classes!/:1.0.0-SNAPSHOT]
	at no.fdk.imcat.service.AltinnHarvest.getHarvestSources(AltinnHarvest.java:112) [classes!/:1.0.0-SNAPSHOT]
	at no.fdk.imcat.service.InformationmodelHarvester.getAllHarvestSources(InformationmodelHarvester.java:74) [classes!/:1.0.0-SNAPSHOT]
	at no.fdk.imcat.service.InformationmodelHarvester.harvestAll(InformationmodelHarvester.java:44) [classes!/:1.0.0-SNAPSHOT]
	at no.fdk.imcat.harvester.HarvestExecutor.lambda$harvestLoop$0(HarvestExecutor.java:41) [classes!/:1.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]

```

**Comment by NilsOveTen** [comment]
Ikke aktuell etter https://github.com/Informasjonsforvaltning/fdk-informationmodel-harvester/issues/46
