### ISSUE TITLE
502 ved tidsstyrt høsting av fdk-model-publisher

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-informationmodel-harvester#99]
Det ser ikke ut som fdk-informationmodel-harvester er tålmodig nok, evt at fdk-model-publisher ikke makter å svare på 6-timers intervallene.
Ser ut til å fungere fint å initiere en egen høsting utenfor høsteintervallene.

 no.fdk.fdk_informationmodel_harvester.harvester.HarvestException: Harvest failed for https://publishers.fellesdatakatalog.digdir.no/fdk-model-publisher/catalog responded with 502, harvest will be aborted
	at no.fdk.fdk_informationmodel_harvester.adapter.InformationModelAdapter.getInformationModels(InformationModelAdapter.kt:26)
	at no.fdk.fdk_informationmodel_harvester.harvester.InformationModelHarvester.harvestInformationModelCatalog(InformationModelHarvester.kt:71)
	at no.fdk.fdk_informationmodel_harvester.harvester.HarvesterActivity$initiateHarvest$1$1$3$1.invokeSuspend(HarvesterActivity.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by valosnah** [comment]
Ser ut til å ha vært issue med minneproblemer. Feil ser ikke ut til å oppstå når memory-req har blitt økt. Står til observasjon over helga

**Comment by valosnah** [comment]
Feil ikke lenger observert etter minneøking. fdk-model-publisher måtte også ha mer minne.
